# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 000da52f61f14750d704843e271e4aa4ca3e949fbbb83927c902a95edb4d55057a39d046a39bc4d04bb4d83cbdc4894134d251c832a4e2cb0f090f0c75b90e96

test:
  secret_key_base: ada688d3395fee0aba71ba90cfb5313430532b09bae1eccbdcc3911dba258b942e74da85314486d0173decbdd12e64a47006bb97b1e54f736501fb5210d6a073

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
